version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: ict05-mariadb
    environment:
      MARIADB_DATABASE: ict05final
      MARIADB_USER: ictuser
      MARIADB_PASSWORD: ictpass123
      MARIADB_ROOT_PASSWORD: rootpass123
    ports:
      - "3306:3306"   # 나중에 외부 막고 싶으면 이 줄 삭제해도 됨
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: