# 로그 레벨
logging.level.root=WARN
logging.level.com.boot=WARN

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://db:3306/ict05final
spring.datasource.username=ictuser
spring.datasource.password=ictpass123
# 파일 출력
logging.file.name=logs/prod.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n